**Import the NumPy library as np.**

>



In [1]:
import numpy as np

**Find the maximum value in the array data.**

In [2]:

data = np.array([1,2,3,4])
data.max()




4

 **Find the minimum value in the array data.**

In [3]:
data.min()


1

**Create an array of size 4 filled with ones.**



In [4]:
data1=np.ones(4)
data1




array([1., 1., 1., 1.])

**Create an array of size 4 filled with zeros.**



In [5]:
data2=np.zeros(4)
data2


array([0., 0., 0., 0.])

**Element-wise addition of arrays data and data1.**

In [6]:
data+data1





array([2., 3., 4., 5.])

**Element-wise subtraction of array data from data1.**

In [7]:
data1-data


array([ 0., -1., -2., -3.])

**Element-wise division of array data1 by data.**

In [8]:
data1/data



array([1.        , 0.5       , 0.33333333, 0.25      ])

**Element-wise multiplication of arrays data1 and data.**



In [9]:
data1*data


array([1., 2., 3., 4.])

**Multiply each element in array data by 8.**


In [10]:
data*8


array([ 8, 16, 24, 32])

**Slicing**

In [11]:

data[0:10]


array([1, 2, 3, 4])

In [12]:
data[1:]

array([2, 3, 4])

In [13]:
data[-1:]


array([4])

In [14]:
data[:-1]


array([1, 2, 3])

**Perform dot product of array data with scalar value 6.**

In [15]:
data.dot(6)



array([ 6, 12, 18, 24])

**Create a 2D array (matrix) from a nested list.**

In [16]:
matrix=np.array([[1,2,3],[6,7,8]])

In [17]:
matrix2=np.array([[6,6,6],[8,8,9]])




**Element-wise operations of matrices matrix and matrix2.**

In [18]:
matrix+matrix2

array([[ 7,  8,  9],
       [14, 15, 17]])

In [19]:
matrix/matrix2


array([[0.16666667, 0.33333333, 0.5       ],
       [0.75      , 0.875     , 0.88888889]])

In [20]:
matrix*matrix2

array([[ 6, 12, 18],
       [48, 56, 72]])

**Accessing Elements of a matrix**

In [21]:
matrix[0]

array([1, 2, 3])

In [22]:

matrix[0:1,2]



array([3])

**Reshape the matrix matrix into a 2x3 matrix.**

In [23]:
matrix.reshape(2,3)

array([[1, 2, 3],
       [6, 7, 8]])

**Reshape the matrix matrix into a 3x2 matrix.**

In [24]:


matrix.reshape(3,2)

array([[1, 2],
       [3, 6],
       [7, 8]])

**Create a 3D array filled with ones and accesses a specific element.**

In [25]:
a=np.ones((4,3,3))
a[1][2][1]

1.0

In [26]:


a=np.random.random((4,3,3))

In [27]:

a

array([[[0.5771293 , 0.53206019, 0.06045957],
        [0.85063895, 0.08251412, 0.19953785],
        [0.26812712, 0.80181924, 0.18676438]],

       [[0.87479065, 0.45956801, 0.40814455],
        [0.20899468, 0.92433699, 0.53247718],
        [0.50153   , 0.21819244, 0.56488905]],

       [[0.20620606, 0.08840362, 0.23730381],
        [0.18246395, 0.66970827, 0.98029623],
        [0.22832291, 0.15485549, 0.26578593]],

       [[0.38420386, 0.53289792, 0.21382746],
        [0.19290373, 0.48005627, 0.04555157],
        [0.82303975, 0.38417848, 0.87548542]]])

**Return some information about the matrix**

In [28]:
a.ndim


3

In [29]:
matrix.dtype


dtype('int64')

In [30]:
matrix.shape


(2, 3)

In [31]:
matrix.itemsize

8

In [32]:
a.dtype



dtype('float64')

In [33]:
a.shape

(4, 3, 3)

**Broadcasting Operations**

In [34]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([10, 20, 30])
result = arr1 + arr2  # Broadcasting arr2 to match the shape of arr1
print("Broadcasting Result:")
print(result)

Broadcasting Result:
[[11 22 33]
 [14 25 36]]


**Array Manipulation**

In [35]:

arr3d = np.arange(24).reshape(2, 3, 4)
flattened_arr = arr3d.flatten()  # Flatten the 3D array
print("\nFlattened Array:")
print(flattened_arr)

arr4 = np.array([[7, 8, 9], [10, 11, 12]])
concatenated_arr = np.concatenate((arr1, arr4), axis=0)  # Concatenate arrays along rows
print("\nConcatenated Array:")
print(concatenated_arr)




Flattened Array:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]

Concatenated Array:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


 **Array Comparison**

In [37]:
comparison_result = arr1 > 3
print("\nComparison Result:")
print(comparison_result)


Comparison Result:
[[False False False]
 [ True  True  True]]


**Array Indexing and Fancy Indexing**

In [38]:

arr5 = np.array([1, 2, 3, 4, 5])
indices = [1, 3, 4]
selected_elements = arr5[indices]  # Fancy indexing
print("\nSelected Elements using Fancy Indexing:")
print(selected_elements)


Selected Elements using Fancy Indexing:
[2 4 5]


**Mathematical Functions**

In [39]:
arr6 = np.array([0, np.pi/2, np.pi])
sin_values = np.sin(arr6)  # Applying sin function
print("\nSin Values:")
print(sin_values)


Sin Values:
[0.0000000e+00 1.0000000e+00 1.2246468e-16]


**Linear Algebra**

In [40]:
matrix_a = np.array([[1, 2], [3, 4]])
matrix_b = np.array([[5, 6], [7, 8]])
matrix_product = np.matmul(matrix_a, matrix_b)  # Matrix multiplication
print("\nMatrix Product:")
print(matrix_product)


Matrix Product:
[[19 22]
 [43 50]]


**Statistics**

In [41]:
arr7 = np.array([1, 2, 3, 4, 5])
mean_value = np.mean(arr7)
print("\nMean Value:")
print(mean_value)


Mean Value:
3.0


**Random Sampling**

In [42]:
random_samples = np.random.normal(loc=0, scale=1, size=(3, 3))  # Generate random samples from a normal distribution
print("\nRandom Samples:")
print(random_samples)



Random Samples:
[[-0.02098063  0.71077838 -1.11733568]
 [ 2.08557252  1.13472184  0.36453904]
 [ 0.57834286 -0.04464303 -1.4058665 ]]
