<a href="https://colab.research.google.com/github/ShaluPriya-R01/shalu-priya/blob/main/numpy1_aggregation_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
#aggregation
data = np.array([1,2,3,4])
data.max()




4

In [ ]:
data.min()


1

In [ ]:
data1=np.ones(4)
data1




array([1., 1., 1., 1.])

In [ ]:
data2=np.zeros(4)
data2


array([0., 0., 0., 0.])

In [ ]:
data+data1





array([2., 3., 4., 5.])

In [ ]:
data1-data


array([ 0., -1., -2., -3.])

In [ ]:
data1/data



array([1.        , 0.5       , 0.33333333, 0.25      ])

In [ ]:
data1*data


array([1., 2., 3., 4.])

In [ ]:
data*8


array([ 8, 16, 24, 32])

In [ ]:
#slicing
data[0:10]


array([1, 2, 3, 4])

In [ ]:
data[1:]

array([2, 3, 4])

In [ ]:
data[-1:]


array([4])

In [ ]:
data[:-1]


array([1, 2, 3])

In [ ]:
data.dot(6)



array([ 6, 12, 18, 24])

In [ ]:
matrix=np.array([[1,2,3],[6,7,8]])

In [ ]:
matrix2=np.array([[6,6,6],[8,8,9]])




In [ ]:
matrix+matrix2

array([[ 7,  8,  9],
       [14, 15, 17]])

In [ ]:
matrix/matrix2


array([[0.16666667, 0.33333333, 0.5       ],
       [0.75      , 0.875     , 0.88888889]])

In [ ]:
matrix*matrix2

array([[ 6, 12, 18],
       [48, 56, 72]])

In [ ]:
matrix[0]

array([1, 2, 3])

In [ ]:

matrix[0:1,2]



array([3])

In [ ]:
matrix.reshape(2,3)

array([[1, 2, 3],
       [6, 7, 8]])

In [ ]:


matrix.reshape(3,2)

array([[1, 2],
       [3, 6],
       [7, 8]])

In [ ]:
a=np.ones((4,3,3))
a[1][2][1]

1.0

In [ ]:

a=np.random.random((4,3,3))

In [ ]:

a

array([[[0.29647689, 0.84747604, 0.51995147],
        [0.9319587 , 0.14760941, 0.40728893],
        [0.48136496, 0.19886047, 0.57846497]],

       [[0.26142605, 0.46348162, 0.98543516],
        [0.51401793, 0.15782792, 0.09179631],
        [0.1335494 , 0.4906908 , 0.9812028 ]],

       [[0.11328866, 0.67731074, 0.91014083],
        [0.70399288, 0.04171583, 0.96359897],
        [0.05236495, 0.04812665, 0.68349727]],

       [[0.14817809, 0.70331966, 0.3101162 ],
        [0.46579382, 0.20719557, 0.49483803],
        [0.92087533, 0.59218705, 0.81059358]]])

In [ ]:
a.ndim


3

In [ ]:
matrix.dtype


dtype('int64')

In [ ]:
matrix.shape


(2, 3)

In [ ]:
matrix.itemsize

8

In [ ]:
a.dtype



dtype('float64')

In [ ]:
a.shape

(4, 3, 3)